### PR TITLE
Fixes #11 - Update sonar.sh to fail if rhc port-forward fails

### LINKED ISSUE #11: Update sonar.sh to fail if rhc port-forward fails
If you have multiple servers configured for openshift in rhc command the sonar.sh script should handle the case when you have the wrong server used for the port-forward.  Right now it fails to do the port forward but the builds continue but are not able to publish.  So unless you're paying attention you might not notice.

### PR DESCRIPTION
**Pull request by luan-cestari**
More info https://github.com/lightblue-platform/lightblue/issues/11

### CODE REVIEW

File: etc/sonar.sh [hunk 1]
```diff
@@ -17,15 +17,24 @@ if [ $(curl -I -s https://sonar-lightblue.rhcloud.com/ -s | head -n1 | grep "HTT
...
-# forward ports from openshift (assumes current server is openshift online and you're a member of the lightblue namespace)
-rhc port-forward sonar -n lightblue &
+# forward ports from openshift (assumes current server is openshift online and you're a member of the lightblue namespace). A new mark file will eb created if the return value of the rhc command is different than 0
+rhc port-forward sonar -n lightblue || echo $? > rhc-port-forward-status  &
 
 # wait a bit for port forwarding to fire up
 sleep 10
 
+# if the file exists, log the error and exit 1
+if [ -f "rhc-port-forward-status" ]
```
Comment (jewzaam) [inline etc/sonar.sh]: This check can come before the `sleep 10` above so the script fails faster.

Comment (luan-cestari) [inline etc/sonar.sh]: I don't think we should do that as the '&' would make the process run asynchronously in background , which it can take some time even to connect to the openshift, so the rhc command could not make the result in time to the if statement gives the right/expected output

**Comment by luan-cestari** [comment]
Updated the commented line

File: etc/sonar.sh (hunk 1 above)
Comment (jewzaam) [inline etc/sonar.sh]: Good point, thank you.

**Comment by jewzaam** [comment]
Two things to clean up:
* please add `rhc-port-forward-status` to `.gitignore`
* please rm `rhc-port-forward-status` before exiting the process

**Comment by luan-cestari** [comment]
Let me know if I can make the change across the other repositories

**Comment by jewzaam** [comment]
Go for it.  Should be an exact copy of this script (plus .gitignore updates) right?
